"""Shared span-level filters used by claim extraction and citation parsing.

Claim filters apply before deterministic claim extraction. Citation filters are
narrower so guidance/meta spans can be suppressed as manufacturer claims while
still exposing citation markers for provenance.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from locuslab.models import Document, DocumentKind, Span, SpanLocationKind

# Section name matches "References", "Bibliography", "Bibliographies", "Sources".
BIBLIOGRAPHY_SECTION = re.compile(
    r"\b(?:references?|bibliograph(?:y|ies)|sources)\b",
    re.IGNORECASE,
)

# Text starting with REF-NNN. (optional leading whitespace, mandatory trailing dot+space).
BIBLIOGRAPHY_PREFIX = re.compile(r"^\s*REF-\d+\.\s", re.IGNORECASE)

# PDF-style numbered reference lines, e.g.:
# "1. Smith J. et al. Clinical performance review. 2023."
# The year must sit in a citation-typical position (preceded by ., , ; ( [ – —)
# so that body prose like "1. Jones A. validated the 2023 protocol..." does not
# match — the year there sits after "the", not after citation punctuation.
NUMBERED_REFERENCE_LINE = re.compile(
    r"^\s*\d{1,3}\.\s+"
    r"[A-Z][A-Za-z'\-]+"
    r"(?:\s+[A-Z]\.|\s+et\s+al\.?)"
    r"[^\n]*?[\.\,\;\(\[–—]\s*(?:19|20)\d{2}\b",
    re.IGNORECASE,
)

# Table-of-contents lines generated by PDFs commonly contain leader dots and
# a trailing page number.
TOC_LEADER_LINE = re.compile(
    r"^\s*(?:\d+(?:\.\d+)*\s+)?[A-Za-z][A-Za-z0-9 /,&()'\-]{2,}"
    r"\s+\.{3,}\s*\d+\s*$"
)

# Short numbered section headings without a parsed section, common for PDF PAGE
# spans when pypdf emits a heading as its own page/span.
NUMBERED_HEADING_ONLY = re.compile(
    r"^\s*\d+(?:\.\d+)*\.?\s+[A-Za-z][A-Za-z0-9 /,&()'\-]{3,120}$"
)

PDF_PAGE_MARKER = re.compile(
    r"\b(?:page\s+)?\d+\s*(?:\(\s*\d+\s*\)|of\s+\d+)",
    re.IGNORECASE,
)

PDF_CHROME_TEXT = re.compile(r"\b(?:document|rev\.?|revision)\b", re.IGNORECASE)

GUIDANCE_META_TERMS = re.compile(
    r"\b(?:this\s+guidance|guidance\s+document|template)\b",
    re.IGNORECASE,
)

GUIDANCE_MODAL_TERMS = re.compile(
    r"\b(?:shall|should|recommended)\b",
    re.IGNORECASE,
)

APPENDIX_HEADING = re.compile(r"^\s*appendix\b", re.IGNORECASE)
PLACEHOLDER_LINE = re.compile(
    r"^\s*\[[^\]]*(?:insert|placeholder|to be completed)[^\]]*\]\s*$",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class SpanClaimExtractionDecision:
    """Observable claim-extraction decision for a span."""

    suppress_claim_extraction: bool
    reasons: tuple[str, ...] = ()
    retain_as_source_anchor: bool = False


def classify_span_for_claim_extraction(
    span: Span,
    doc: Document | None = None,
) -> SpanClaimExtractionDecision:
    """Classify whether a span should emit claim candidates.

    A suppressed claim span may still be useful as a source/citation anchor, so
    callers should not treat this decision as permission to drop the span from
    the evidence surface.
    """
    reasons: list[str] = []
    retain_as_source_anchor = False

    if is_bibliography_span(span):
        reasons.append("bibliography")
        retain_as_source_anchor = True
    if is_table_of_contents_span(span):
        reasons.append("table_of_contents")
    if is_heading_span(span):
        reasons.append("heading")
    if is_pdf_chrome_span(span):
        reasons.append("pdf_chrome")
    if is_appendix_template_span(span):
        reasons.append("appendix_template")
    if is_guidance_meta_span(span, doc):
        reasons.append("guidance_meta")
        retain_as_source_anchor = True

    return SpanClaimExtractionDecision(
        suppress_claim_extraction=bool(reasons),
        reasons=tuple(reasons),
        retain_as_source_anchor=retain_as_source_anchor,
    )


def is_non_claim_noise_span(span: Span, doc: Document | None = None) -> bool:
    """True when a span should not emit claim candidates."""
    return classify_span_for_claim_extraction(span, doc).suppress_claim_extraction


def is_citation_noise_span(span: Span) -> bool:
    """True when a span should not emit citation mentions.

    This is intentionally narrower than claim suppression. Guidance/meta prose
    can be suppressed from manufacturer claim extraction while still exposing
    citation markers for provenance.
    """
    return (
        is_bibliography_span(span)
        or is_table_of_contents_span(span)
        or is_heading_span(span)
        or is_pdf_chrome_span(span)
        or is_appendix_template_span(span)
    )


def is_bibliography_span(span: Span) -> bool:
    """True when the span is part of a references/bibliography section
    or starts with a REF-NNN. prefix.
    """
    section = span.section or ""
    if BIBLIOGRAPHY_SECTION.search(section):
        return True
    text = span.text
    if BIBLIOGRAPHY_PREFIX.match(text):
        return True
    lines = _non_empty_lines(text)
    if not lines:
        return False
    first_line = lines[0].strip().lower().rstrip(":")
    if first_line in {"references", "reference list", "bibliography", "sources"}:
        return True
    numbered_reference_count = sum(1 for line in lines if NUMBERED_REFERENCE_LINE.match(line))
    return span.location.kind == SpanLocationKind.PAGE and numbered_reference_count >= 2


def is_heading_span(span: Span) -> bool:
    """True when the span is a heading rather than body evidence text.

    The docx_reader emits Heading-styled paragraphs this way; the heading text
    becomes both the span text and the current section.
    """
    text = " ".join(span.text.strip().split())
    if not text:
        return False
    raw_section = span.section
    section = (raw_section or "").strip()
    if span.location.kind == SpanLocationKind.PARAGRAPH and section:
        return text == " ".join(section.split())
    if span.location.kind == SpanLocationKind.PAGE and raw_section is None:
        return _looks_like_pdf_heading(text)
    return False


def is_table_of_contents_span(span: Span) -> bool:
    """True for PDF table-of-contents spans."""
    lines = _non_empty_lines(span.text)
    if not lines:
        return False
    first_line = lines[0].strip().lower()
    toc_line_count = sum(1 for line in lines if TOC_LEADER_LINE.match(line))
    if "table of contents" in first_line and toc_line_count >= 1:
        return True
    return span.location.kind == SpanLocationKind.PAGE and toc_line_count >= 3


def is_pdf_chrome_span(span: Span) -> bool:
    """True for short PDF header/footer/page-marker spans."""
    if span.location.kind != SpanLocationKind.PAGE:
        return False
    lines = _non_empty_lines(span.text)
    if not lines or len(lines) > 4:
        return False
    text = " ".join(lines)
    has_document_chrome = bool(PDF_CHROME_TEXT.search(text))
    return has_document_chrome and bool(PDF_PAGE_MARKER.search(text))


def is_appendix_template_span(span: Span) -> bool:
    """True for appendix placeholder spans, not dossier evidence."""
    lines = _non_empty_lines(span.text)
    if not lines:
        return False
    if not APPENDIX_HEADING.match(lines[0]):
        return False
    placeholder_count = sum(1 for line in lines[1:] if PLACEHOLDER_LINE.match(line))
    return placeholder_count >= 2


def is_guidance_meta_span(span: Span, doc: Document | None = None) -> bool:
    """True for guidance/template prose that should not emit manufacturer claims."""
    if doc is not None and not _is_guidance_like_document(doc):
        return False
    text = " ".join(span.text.strip().split())
    if not text:
        return False
    if not GUIDANCE_META_TERMS.search(text):
        return False
    return bool(GUIDANCE_MODAL_TERMS.search(text))


def _looks_like_pdf_heading(text: str) -> bool:
    if len(text) > 140:
        return False
    if text.endswith((".", ";", ":")):
        return False
    if len(text.split()) > 12:
        return False
    return bool(NUMBERED_HEADING_ONLY.match(text))


def _non_empty_lines(text: str) -> list[str]:
    return [line.strip() for line in text.splitlines() if line.strip()]


def _is_guidance_like_document(doc: Document) -> bool:
    return doc.kind == DocumentKind.OTHER
